using System.Globalization;
CultureInfo.CurrentCulture = CultureInfo.InvariantCulture;

string customer = "Riverside Dental";
string item = "Printer paper (case)";
int quantity = 12;
decimal unitPrice = 38.50m;
decimal subtotal = quantity * unitPrice;
decimal discount = Math.Round(subtotal * 0.05m, 2, MidpointRounding.AwayFromZero);
decimal discounted = subtotal;
discounted -= discount;
decimal tax = Math.Round(discounted * 0.07m, 2, MidpointRounding.AwayFromZero);
decimal amountDue = discounted;
amountDue += tax;
Console.WriteLine($"Invoice for {customer}");
Console.WriteLine($"{quantity} x {item}");
Console.WriteLine($"{"Amount (USD)",-14} | {"Value",10}");
Console.WriteLine($"{"Subtotal",-14} | {subtotal,10:F2}");
Console.WriteLine($"{"Discount",-14} | {-discount,10:F2}");
Console.WriteLine($"{"Tax",-14} | {tax,10:F2}");
Console.WriteLine($"{"Total",-14} | {amountDue,10:F2}");
