# Lab

- Use this lab to practice the chapter's coding skills in runnable C# code.
- Sign in from the account menu before you start working on the lab.
- Launch Live Code (the rocket) to write and run code in the coding cells.
- Multiple submissions are allowed. The highest score is kept.


## 1. Ring Up Sales with Static Methods

A coffee shop has two registers, `Front` and `Drive-thru`. This first version is procedural: the running total is a local variable in the calling code, and the static method `RingUp` receives it as a parameter and returns the new total.

Complete `RingUp` so it computes the line amount (`price * quantity`), prints the line as `  2 x $4.50 = $9.00`, and adds the line amount to `newTotal`. Notice that the calling code must keep one total variable per register and remember to assign the result back every time.


In [ ]:
using System;

decimal frontTotal = 0m;
decimal driveThruTotal = 0m;

frontTotal = RingUp(frontTotal, 4.50m, 2);
driveThruTotal = RingUp(driveThruTotal, 3.25m, 1);
frontTotal = RingUp(frontTotal, 12.00m, 1);

Console.WriteLine($"Front total: ${frontTotal:F2}");
Console.WriteLine($"Drive-thru total: ${driveThruTotal:F2}");

static decimal RingUp(decimal total, decimal price, int quantity)
{
    decimal newTotal = total;

    // Your code starts here.



    // Your code ends here.

    return newTotal;
}


In [ ]:
using System;

decimal frontTotal = 0m;
decimal driveThruTotal = 0m;

frontTotal = RingUp(frontTotal, 4.50m, 2);
driveThruTotal = RingUp(driveThruTotal, 3.25m, 1);
frontTotal = RingUp(frontTotal, 12.00m, 1);

Console.WriteLine($"Front total: ${frontTotal:F2}");
Console.WriteLine($"Drive-thru total: ${driveThruTotal:F2}");

static decimal RingUp(decimal total, decimal price, int quantity)
{
    decimal newTotal = total;

    decimal lineAmount = price * quantity;
    Console.WriteLine($"  {quantity} x ${price:F2} = ${lineAmount:F2}");
    newTotal = total + lineAmount;

    return newTotal;
}


  2 x $4.50 = $9.00
  1 x $3.25 = $3.25
  1 x $12.00 = $12.00
Front total: $21.00
Drive-thru total: $3.25


## 2. Convert the Register to a Class

Now make each register an object that remembers its own total. Ask what each variable from question 1 should become:

- The running `total` must be remembered *between* calls to `RingUp`, and each register has its own, so it becomes a private **instance field**. It is no longer a parameter or a return value.
- `lineAmount` is computed, printed, added, and then never needed again, so it stays a **local variable** inside `RingUp`. Making it a field would only leave a stale value lying around.
- The register's `name` is set once by the **constructor** and exposed through a read-only `Name` property; `Total` is a read-only property so outside code can read the total but not overwrite it.

Complete the instance method `RingUp`. It no longer takes or returns a total. Print each line with the register name, as in `  Front: 2 x $4.50 = $9.00`.


In [ ]:
using System;

CashRegister front = new CashRegister("Front");
CashRegister driveThru = new CashRegister("Drive-thru");

front.RingUp(4.50m, 2);
driveThru.RingUp(3.25m, 1);
front.RingUp(12.00m, 1);

Console.WriteLine($"{front.Name} total: ${front.Total:F2}");
Console.WriteLine($"{driveThru.Name} total: ${driveThru.Total:F2}");

class CashRegister
{
    private string name;
    private decimal total;

    public CashRegister(string name)
    {
        this.name = name;
        total = 0m;
    }

    public string Name
    {
        get { return name; }
    }

    public decimal Total
    {
        get { return total; }
    }

    public void RingUp(decimal price, int quantity)
    {
        // Your code starts here.



        // Your code ends here.
    }
}


In [ ]:
using System;

CashRegister front = new CashRegister("Front");
CashRegister driveThru = new CashRegister("Drive-thru");

front.RingUp(4.50m, 2);
driveThru.RingUp(3.25m, 1);
front.RingUp(12.00m, 1);

Console.WriteLine($"{front.Name} total: ${front.Total:F2}");
Console.WriteLine($"{driveThru.Name} total: ${driveThru.Total:F2}");

class CashRegister
{
    private string name;
    private decimal total;

    public CashRegister(string name)
    {
        this.name = name;
        total = 0m;
    }

    public string Name
    {
        get { return name; }
    }

    public decimal Total
    {
        get { return total; }
    }

    public void RingUp(decimal price, int quantity)
    {
        decimal lineAmount = price * quantity;
        Console.WriteLine($"  {name}: {quantity} x ${price:F2} = ${lineAmount:F2}");
        total += lineAmount;
    }
}


  Front: 2 x $4.50 = $9.00
  Drive-thru: 1 x $3.25 = $3.25
  Front: 1 x $12.00 = $12.00
Front total: $21.00
Drive-thru total: $3.25


## 3. Validate the Cashier Property

Each register now records which cashier is signed in. A cashier can change during the day, so `Cashier` needs a `set` accessor, but a blank name must never be stored. The constructor assigns through the property (`Cashier = cashier;`) instead of the field, so the same rule protects new registers too.

Complete the `set` accessor: if `value` is null, empty, or only spaces (`string.IsNullOrWhiteSpace`), throw an `ArgumentException` with the message `Cashier name cannot be blank.`; otherwise store the trimmed name in the `cashier` field. The calling code catches the exception, so the register keeps its previous cashier.


In [ ]:
using System;

CashRegister front = new CashRegister("Front", "Avery");
front.RingUp(4.50m, 2);

front.Cashier = "  Jordan ";   // shift change
front.RingUp(12.00m, 1);

try
{
    front.Cashier = "   ";
}
catch (ArgumentException ex)
{
    Console.WriteLine($"Rejected: {ex.Message}");
}

Console.WriteLine($"{front.Name} cashier: {front.Cashier}, total: ${front.Total:F2}");

class CashRegister
{
    private string name;
    private string cashier = "";
    private decimal total;

    public CashRegister(string name, string cashier)
    {
        this.name = name;
        Cashier = cashier;   // goes through the validating setter
        total = 0m;
    }

    public string Name
    {
        get { return name; }
    }

    public decimal Total
    {
        get { return total; }
    }

    public string Cashier
    {
        get { return cashier; }
        set
        {
            // Your code starts here.



            // Your code ends here.
        }
    }

    public void RingUp(decimal price, int quantity)
    {
        decimal lineAmount = price * quantity;
        Console.WriteLine($"  {cashier} at {name}: {quantity} x ${price:F2} = ${lineAmount:F2}");
        total += lineAmount;
    }
}


In [ ]:
using System;

CashRegister front = new CashRegister("Front", "Avery");
front.RingUp(4.50m, 2);

front.Cashier = "  Jordan ";   // shift change
front.RingUp(12.00m, 1);

try
{
    front.Cashier = "   ";
}
catch (ArgumentException ex)
{
    Console.WriteLine($"Rejected: {ex.Message}");
}

Console.WriteLine($"{front.Name} cashier: {front.Cashier}, total: ${front.Total:F2}");

class CashRegister
{
    private string name;
    private string cashier = "";
    private decimal total;

    public CashRegister(string name, string cashier)
    {
        this.name = name;
        Cashier = cashier;   // goes through the validating setter
        total = 0m;
    }

    public string Name
    {
        get { return name; }
    }

    public decimal Total
    {
        get { return total; }
    }

    public string Cashier
    {
        get { return cashier; }
        set
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new ArgumentException("Cashier name cannot be blank.");
            }
            cashier = value.Trim();
        }
    }

    public void RingUp(decimal price, int quantity)
    {
        decimal lineAmount = price * quantity;
        Console.WriteLine($"  {cashier} at {name}: {quantity} x ${price:F2} = ${lineAmount:F2}");
        total += lineAmount;
    }
}


  Avery at Front: 2 x $4.50 = $9.00
  Jordan at Front: 1 x $12.00 = $12.00
Rejected: Cashier name cannot be blank.
Front cashier: Jordan, total: $21.00


## 4. Share Store-Wide Data with Static Members

The shop now rings up a whole receipt at once with `Checkout(decimal[] prices)`, which replaces `RingUp`. Decide where each piece of data belongs:

- **Static field** `nextReceiptNumber`: receipt numbers must be unique across the *whole store*, so all registers share one counter. One copy for the class, not one per register.
- **Static property** `TaxRate`: there is one sales-tax rate for the store. Changing it once (`CashRegister.TaxRate = 0.07m;`) changes it for every register.
- **Static method** `Money`: it formats a number and remembers nothing, so it stays a stateless static helper. Turning it into an instance method would gain nothing.
- **Instance fields** `total` and `receiptCount`: each register's own running results.
- **Local variables** `subtotal`, `tax`, `amountDue`, and `receipt`: they start over for every checkout and mean nothing afterward, so they stay local, just like `lineAmount` did.

Complete `Checkout`: add up the prices into `subtotal`, compute `tax` as `Math.Round(subtotal * TaxRate, 2)`, take the next receipt number (then advance the shared counter), add the amount due to `total`, add 1 to `receiptCount`, and print the receipt in this format:

```text
Receipt 1001 (Front, Avery): $21.00 + tax $1.68 = $22.68
```


In [ ]:
using System;

CashRegister front = new CashRegister("Front", "Avery");
CashRegister driveThru = new CashRegister("Drive-thru", "Sam");

front.Checkout(new decimal[] { 4.50m, 4.50m, 12.00m });
driveThru.Checkout(new decimal[] { 3.25m });

CashRegister.TaxRate = 0.07m;   // one change, every register sees it
front.Checkout(new decimal[] { 2.75m, 6.00m });
driveThru.Checkout(new decimal[] { 9.80m, 1.20m });

Console.WriteLine($"{front.Name}: {front.ReceiptCount} receipts, {CashRegister.Money(front.Total)}");
Console.WriteLine($"{driveThru.Name}: {driveThru.ReceiptCount} receipts, {CashRegister.Money(driveThru.Total)}");

class CashRegister
{
    private static int nextReceiptNumber = 1001;   // shared by all registers

    public static decimal TaxRate { get; set; } = 0.08m;

    public static string Money(decimal amount)
    {
        return "$" + amount.ToString("F2");
    }

    private string name;
    private string cashier = "";
    private decimal total;
    private int receiptCount;

    public CashRegister(string name, string cashier)
    {
        this.name = name;
        Cashier = cashier;
        total = 0m;
        receiptCount = 0;
    }

    public string Name
    {
        get { return name; }
    }

    public decimal Total
    {
        get { return total; }
    }

    public int ReceiptCount
    {
        get { return receiptCount; }
    }

    public string Cashier
    {
        get { return cashier; }
        set
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new ArgumentException("Cashier name cannot be blank.");
            }
            cashier = value.Trim();
        }
    }

    public void Checkout(decimal[] prices)
    {
        // Your code starts here.



        // Your code ends here.
    }
}


In [ ]:
using System;

CashRegister front = new CashRegister("Front", "Avery");
CashRegister driveThru = new CashRegister("Drive-thru", "Sam");

front.Checkout(new decimal[] { 4.50m, 4.50m, 12.00m });
driveThru.Checkout(new decimal[] { 3.25m });

CashRegister.TaxRate = 0.07m;   // one change, every register sees it
front.Checkout(new decimal[] { 2.75m, 6.00m });
driveThru.Checkout(new decimal[] { 9.80m, 1.20m });

Console.WriteLine($"{front.Name}: {front.ReceiptCount} receipts, {CashRegister.Money(front.Total)}");
Console.WriteLine($"{driveThru.Name}: {driveThru.ReceiptCount} receipts, {CashRegister.Money(driveThru.Total)}");

class CashRegister
{
    private static int nextReceiptNumber = 1001;   // shared by all registers

    public static decimal TaxRate { get; set; } = 0.08m;

    public static string Money(decimal amount)
    {
        return "$" + amount.ToString("F2");
    }

    private string name;
    private string cashier = "";
    private decimal total;
    private int receiptCount;

    public CashRegister(string name, string cashier)
    {
        this.name = name;
        Cashier = cashier;
        total = 0m;
        receiptCount = 0;
    }

    public string Name
    {
        get { return name; }
    }

    public decimal Total
    {
        get { return total; }
    }

    public int ReceiptCount
    {
        get { return receiptCount; }
    }

    public string Cashier
    {
        get { return cashier; }
        set
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new ArgumentException("Cashier name cannot be blank.");
            }
            cashier = value.Trim();
        }
    }

    public void Checkout(decimal[] prices)
    {
        decimal subtotal = 0m;
        foreach (decimal price in prices)
        {
            subtotal += price;
        }

        decimal tax = Math.Round(subtotal * TaxRate, 2);
        decimal amountDue = subtotal + tax;

        int receipt = nextReceiptNumber;
        nextReceiptNumber++;

        total += amountDue;
        receiptCount++;

        Console.WriteLine($"Receipt {receipt} ({name}, {cashier}): {Money(subtotal)} + tax {Money(tax)} = {Money(amountDue)}");
    }
}


Receipt 1001 (Front, Avery): $21.00 + tax $1.68 = $22.68
Receipt 1002 (Drive-thru, Sam): $3.25 + tax $0.26 = $3.51
Receipt 1003 (Front, Avery): $8.75 + tax $0.61 = $9.36
Receipt 1004 (Drive-thru, Sam): $12.00 + tax $0.77 = $12.77
Front: 2 receipts, $32.04
Drive-thru: 2 receipts, $15.28


## 5. Print a Shift Report with ToString

At closing time the manager wants one line per register. Override `ToString` so that `Console.WriteLine(register)` prints the register's state in this format:

```text
Front (Avery): 2 receipts, $32.04
```

Use the instance fields and the static `Money` helper. The report code then keeps the registers in a `List<CashRegister>`, prints each one, and adds up the store total. Each object reports on itself, so the report code never needs to know how a register stores its data.


In [ ]:
using System;
using System.Collections.Generic;

CashRegister front = new CashRegister("Front", "Avery");
CashRegister driveThru = new CashRegister("Drive-thru", "Sam");

front.Checkout(new decimal[] { 4.50m, 4.50m, 12.00m });
driveThru.Checkout(new decimal[] { 3.25m });
CashRegister.TaxRate = 0.07m;
front.Checkout(new decimal[] { 2.75m, 6.00m });
driveThru.Checkout(new decimal[] { 9.80m, 1.20m });

List<CashRegister> registers = new List<CashRegister> { front, driveThru };
decimal storeTotal = 0m;

Console.WriteLine("Shift report");
foreach (CashRegister register in registers)
{
    Console.WriteLine(register);
    storeTotal += register.Total;
}
Console.WriteLine($"Store total: {CashRegister.Money(storeTotal)}");

class CashRegister
{
    private static int nextReceiptNumber = 1001;   // shared by all registers

    public static decimal TaxRate { get; set; } = 0.08m;

    public static string Money(decimal amount)
    {
        return "$" + amount.ToString("F2");
    }

    private string name;
    private string cashier = "";
    private decimal total;
    private int receiptCount;

    public CashRegister(string name, string cashier)
    {
        this.name = name;
        Cashier = cashier;
        total = 0m;
        receiptCount = 0;
    }

    public string Name
    {
        get { return name; }
    }

    public decimal Total
    {
        get { return total; }
    }

    public int ReceiptCount
    {
        get { return receiptCount; }
    }

    public string Cashier
    {
        get { return cashier; }
        set
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new ArgumentException("Cashier name cannot be blank.");
            }
            cashier = value.Trim();
        }
    }

    public void Checkout(decimal[] prices)
    {
        decimal subtotal = 0m;
        foreach (decimal price in prices)
        {
            subtotal += price;
        }

        decimal tax = Math.Round(subtotal * TaxRate, 2);
        decimal amountDue = subtotal + tax;

        int receipt = nextReceiptNumber;
        nextReceiptNumber++;

        total += amountDue;
        receiptCount++;

        Console.WriteLine($"Receipt {receipt} ({name}, {cashier}): {Money(subtotal)} + tax {Money(tax)} = {Money(amountDue)}");
    }

    public override string ToString()
    {
        string summary = "";

        // Your code starts here.



        // Your code ends here.

        return summary;
    }
}


In [ ]:
using System;
using System.Collections.Generic;

CashRegister front = new CashRegister("Front", "Avery");
CashRegister driveThru = new CashRegister("Drive-thru", "Sam");

front.Checkout(new decimal[] { 4.50m, 4.50m, 12.00m });
driveThru.Checkout(new decimal[] { 3.25m });
CashRegister.TaxRate = 0.07m;
front.Checkout(new decimal[] { 2.75m, 6.00m });
driveThru.Checkout(new decimal[] { 9.80m, 1.20m });

List<CashRegister> registers = new List<CashRegister> { front, driveThru };
decimal storeTotal = 0m;

Console.WriteLine("Shift report");
foreach (CashRegister register in registers)
{
    Console.WriteLine(register);
    storeTotal += register.Total;
}
Console.WriteLine($"Store total: {CashRegister.Money(storeTotal)}");

class CashRegister
{
    private static int nextReceiptNumber = 1001;   // shared by all registers

    public static decimal TaxRate { get; set; } = 0.08m;

    public static string Money(decimal amount)
    {
        return "$" + amount.ToString("F2");
    }

    private string name;
    private string cashier = "";
    private decimal total;
    private int receiptCount;

    public CashRegister(string name, string cashier)
    {
        this.name = name;
        Cashier = cashier;
        total = 0m;
        receiptCount = 0;
    }

    public string Name
    {
        get { return name; }
    }

    public decimal Total
    {
        get { return total; }
    }

    public int ReceiptCount
    {
        get { return receiptCount; }
    }

    public string Cashier
    {
        get { return cashier; }
        set
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new ArgumentException("Cashier name cannot be blank.");
            }
            cashier = value.Trim();
        }
    }

    public void Checkout(decimal[] prices)
    {
        decimal subtotal = 0m;
        foreach (decimal price in prices)
        {
            subtotal += price;
        }

        decimal tax = Math.Round(subtotal * TaxRate, 2);
        decimal amountDue = subtotal + tax;

        int receipt = nextReceiptNumber;
        nextReceiptNumber++;

        total += amountDue;
        receiptCount++;

        Console.WriteLine($"Receipt {receipt} ({name}, {cashier}): {Money(subtotal)} + tax {Money(tax)} = {Money(amountDue)}");
    }

    public override string ToString()
    {
        string summary = "";

        summary = $"{name} ({cashier}): {receiptCount} receipts, {Money(total)}";

        return summary;
    }
}


Receipt 1001 (Front, Avery): $21.00 + tax $1.68 = $22.68
Receipt 1002 (Drive-thru, Sam): $3.25 + tax $0.26 = $3.51
Receipt 1003 (Front, Avery): $8.75 + tax $0.61 = $9.36
Receipt 1004 (Drive-thru, Sam): $12.00 + tax $0.77 = $12.77
Shift report
Front (Avery): 2 receipts, $32.04
Drive-thru (Sam): 2 receipts, $15.28
Store total: $47.32


## Submit

Use the assignment submit panel when it is available in the published book.
